channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=24.3.1
- pip:
  - mlflow==2.20.3
  - cloudpickle==3.1.1
  - imbalanced-learn==0.13.0
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.0.0
  - pytest==8.3.5
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
